version: "2"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - xpack.security.enabled=false
  web:
    image: spikemadden/foodcarts-web
    command: ["./wait-for-it.sh", "es:9200", "--", "python", "app.py"]
    ports:
      - "8000:8000"
